name: Build and Push Hello World NextJS Docker Image to GHCR (initialization purposes only)

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually from the GitHub UI

jobs:
  build-and-push-init:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required to push images to GHCR

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      # Step 3: Convert repository owner to lowercase (docker image names must all be lowercase)
      - name: Set repository owner lowercase
        id: owner_lowercase
        run: echo "owner_lowercase=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Step 4: Build the NextJS app
      - name: Install and Build NextJS App
        run: |
          npm ci # Install dependencies (prefer ci for CI environments)
          npm run build # Build the NextJS app
          
      # Step 5: Build and Push Nginx-NextJS Docker Image
      - name: Build and Push Nginx-NextJS Image
        run: |
          docker build --platform linux/amd64 -t ghcr.io/${{ env.owner_lowercase }}/hello-world-nextjs:v0.0.1 .
          docker push ghcr.io/${{ env.owner_lowercase }}/hello-world-nextjs:v0.0.1
